name: All JDKs on all OSs

on: [push,pull_request]

jobs:
  test:
      runs-on: ubuntu-latest
      
      steps:
        - name: Set up virtual X11
          run: sudo apt-get install xvfb
        - name: Start virtual frame buffer
          run: Xvfb :1 -screen 0 1920x1080x16 &
        - name: set display
          run: export DISPLAY=:1
        - name: Checkout
          uses: actions/checkout@v1
        - uses: actions/setup-java@v3
          with:
            distribution: 'corretto' # See 'Supported distributions' for available options
            java-version: '20'
        - name: Cache Maven packages
          uses: actions/cache@v3
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
        - name: Build with Maven
          run: mvn clean install
        
        - name: Publish test coverage results
          uses: PavanMudigonda/jacoco-reporter@v4.8
          with:
            coverage_results_path: 'coverage/target/site/jacoco-aggregate/jacoco.xml'
            coverage_report_title: 'Test coverage results'
            coverage_report_name: 'Test coverage results'
            github_token: ${{ secrets.GITHUB_TOKEN }}
