name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          
      - name: Set up virtual X11
        run: sudo apt-get install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :1 -screen 0 1920x1080x16 &
      - name: set display
        run: export DISPLAY=:1
      - name: Run coverage test
        run: mvn clean install
        env: 
          DISPLAY: :1
      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: 'coverage/target/site/jacoco-aggregate/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
          dotnet-quality: 'ga'

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.20
        with:
          reports: coverage/target/site/jacoco-aggregate/jacoco.xml
          targetdir: coverage
          reporttypes: Html;MarkdownSummaryGithub
          title: summary
          
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: coverage # Artifact name        
          path: coverage # Directory containing files to upload 
          
      - name: Show Report
        uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Code Coverage
          conclusion: ${{ job.status }}
          output: "{\"summary\":\"coverage\",\"text_description\":\"This will be overridden\"}"
          output_text_description_file: coverage/summary.md
          
      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end
        env:
          DISPLAY: :1
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
