name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          
      - name: Set up virtual X11
        run: sudo apt-get install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1920x1080x16 &
      - name: set display
        run: export DISPLAY=:19
        
      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
    
